Repository karmada-io/dashboard, pull requests merged in 2022-01, with the labels that each got.

#5 DASHBOARD: Add github workflow used to build the karmada-dashboard image
  .github/workflows/push-image.yml
  deploy/karmada-dashboard.yaml
Labels: approved, lgtm, size/M

#6 Update image publish workflow
  .github/workflows/push-image.yml
Labels: approved, size/S, lgtm

#7 Setup PR and issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/flaking-test.md
  .github/ISSUE_TEMPLATE/good-first.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm

#9 update url of yaml in README
  README.md
  deploy/karmada-dashboard.yaml
Labels: kind/documentation, approved, size/XS, lgtm

#8 Setup owner files
  OWNERS
Labels: kind/cleanup, approved, size/XS, lgtm
