Repository karmada-io/dashboard, pull requests merged in 2024-08, with the labels that each got.

#61 filter for namespace and optimize label display
  cmd/api/app/routes/namespace/handler.go
  ui/apps/dashboard/src/components/tag-list/index.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/namespace/index.tsx
  ui/apps/dashboard/src/services/base.ts
  ui/apps/dashboard/src/services/namespace.ts
Labels: approved, size/L, tide/merge-method-squash, lgtm

#77 fix ci build error
  .github/workflows/push-image.yml
  ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/index.tsx
Labels: kind/bug, approved, tide/merge-method-squash, size/XS, kind/flake, lgtm

#81 fix: script error for start test-env
  hack/local-up-karmada.sh
Labels: kind/bug, approved, size/XS, lgtm

#82 fix: new method for generate breadcrumbs
  ui/apps/dashboard/src/components/panel/index.tsx
Labels: kind/bug, approved, lgtm, size/M

#80 Improve Responsive Layout and Sidebar Navigation
  ui/apps/dashboard/src/layout/index.tsx
  ui/apps/dashboard/src/layout/sidebar.tsx
Labels: kind/feature, approved, lgtm, size/M

#83 configmap manage
  cmd/api/app/api.go
  cmd/api/app/routes/configmap/handler.go
  pkg/dataselect/dataselectquery.go
  pkg/resource/common/resourcechannels.go
  pkg/resource/configmap/common.go
  pkg/resource/configmap/detail.go
  pkg/resource/configmap/detail_test.go
  pkg/resource/configmap/list.go
Labels: kind/feature, approved, size/L, tide/merge-method-squash, lgtm

#65 implement statefulset resources
  cmd/api/app/api.go
  cmd/api/app/routes/statefulset/handler.go
  pkg/resource/common/resourcechannels.go
  pkg/resource/statefulset/common.go
  pkg/resource/statefulset/detail.go
  pkg/resource/statefulset/list.go
  pkg/resource/statefulset/pods.go
  ui/apps/dashboard/src/components/tag-list/index.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/index.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/workload-detail-drawer.tsx
  ui/apps/dashboard/src/services/base.ts
  ui/apps/dashboard/src/services/workload.ts
Labels: kind/feature, size/XL, approved, tide/merge-method-squash, lgtm

#85 feat: update err-check cond, add method for create unstructured resou…
  cmd/api/app/routes/unstructured/handler.go
  pkg/client/types.go
  pkg/client/verber.go
  ui/apps/dashboard/src/services/unstructured.ts
Labels: kind/feature, approved, lgtm, size/M

#86 UI for configmap management
  pkg/resource/configmap/list_test.go
  ui/apps/dashboard/package.json
  ui/apps/dashboard/src/hooks/index.ts
  ui/apps/dashboard/src/hooks/use-namespace.ts
  ui/apps/dashboard/src/hooks/use-tag-num.ts
  ui/apps/dashboard/src/pages/multicloud-resource-manage/config/components/config-editor-modal.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/config/components/configmap-table.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/config/components/query-filter.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/config/index.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/config/store.ts
  ui/apps/dashboard/src/pages/multicloud-resource-manage/config/types.ts
  ui/apps/dashboard/src/services/base.ts
  ui/apps/dashboard/src/services/config.ts
  ui/pnpm-lock.yaml
Labels: kind/feature, size/XL, approved, lgtm

#92 Fix antd menu warning by removing inlineCollapsed
  ui/apps/dashboard/src/layout/sidebar.tsx
Labels: kind/cleanup, approved, size/XS, lgtm

#56 Feature/turborepo
  .gitignore
  ui/.changeset/README.md
  ui/.changeset/config.json
  ui/.gitignore
  ui/package.json
  ui/packages/terminal/.prettierignore
  ui/packages/terminal/.prettierrc
  ui/packages/terminal/CHANGELOG.md
  ui/packages/terminal/package.json
  ui/packages/terminal/src/base.ts
  ui/packages/terminal/src/container.ts
  ui/packages/terminal/src/index.tsx
  ui/packages/terminal/src/ttyd.ts
  ui/packages/terminal/src/typing.d.ts
  ui/packages/terminal/src/utils.ts
  ui/packages/terminal/tsconfig.json
  ui/packages/terminal/tsconfig.node.json
  ui/packages/terminal/tsup.config.ts
  ui/packages/terminal/typings.d.ts
  ui/packages/xterm-addon-overlay/.prettierignore
  ui/packages/xterm-addon-overlay/.prettierrc
  ui/packages/xterm-addon-overlay/CHANGELOG.md
  ui/packages/xterm-addon-overlay/package.json
  ui/packages/xterm-addon-overlay/src/index.ts
  ui/packages/xterm-addon-overlay/tsconfig.json
  ui/packages/xterm-addon-overlay/tsconfig.node.json
  ui/packages/xterm-addon-overlay/tsup.config.ts
  ui/packages/xterm-addon-zmodem/.prettierignore
  ui/packages/xterm-addon-zmodem/.prettierrc
  ui/packages/xterm-addon-zmodem/CHANGELOG.md
  ui/packages/xterm-addon-zmodem/package.json
  ui/packages/xterm-addon-zmodem/src/index.ts
  ui/packages/xterm-addon-zmodem/tsconfig.json
  ui/packages/xterm-addon-zmodem/tsconfig.node.json
  ui/packages/xterm-addon-zmodem/tsup.config.ts
  ui/packages/xterm-addon-zmodem/typing.d.ts
  ui/patches/zmodem.js@0.1.10.patch
  ui/pnpm-lock.yaml
  ui/turbo.json
Labels: kind/feature, size/XXL, approved, lgtm

#91 implementing feature of config for karmada dashboard
  artifacts/dashboard/karmada-dashboard-configmap.yaml
  cmd/api/app/api.go
  cmd/api/app/routes/config/handler.go
  cmd/api/app/types/api/v1/config.go
  docs/user-guide.md
  pkg/config/config.go
  pkg/config/model.go
  ui/apps/dashboard/src/layout/sidebar.tsx
  ui/apps/dashboard/src/routes/route.tsx
  ui/apps/dashboard/src/services/dashboard-config.ts
Labels: kind/feature, approved, size/L, tide/merge-method-squash, lgtm

#93 add create secret for k8s v1.24+
  README.md
  deploy/karmada-dashboard-secret.yaml
Labels: kind/feature, approved, size/S, lgtm
