Repository karmada-io/dashboard, pull requests merged in 2024-10, with the labels that each got.

#131 Add: add i18n and translator features
  ui/packages/i18n-tool/i18n.config.js
  ui/packages/i18n-tool/package.json
  ui/packages/i18n-tool/src/index.js
  ui/packages/i18n-tool/src/init.js
  ui/packages/i18n-tool/src/options.js
  ui/packages/i18n-tool/src/scan/ast.js
  ui/packages/i18n-tool/src/scan/index.js
  ui/packages/i18n-tool/src/scan/translate.js
  ui/packages/i18n-tool/src/utils.js
  ui/packages/translators/.gitignore
  ui/packages/translators/.prettierignore
  ui/packages/translators/.prettierrc
  ui/packages/translators/README.md
  ui/packages/translators/package.json
  ui/packages/translators/src/baidu.ts
  ui/packages/translators/src/base.ts
  ui/packages/translators/src/deepl.ts
  ui/packages/translators/src/index.ts
  ui/packages/translators/src/openai.ts
  ui/packages/translators/src/utils.ts
  ui/packages/translators/tsconfig.json
  ui/packages/translators/tsup.config.ts
  ui/packages/translators/typings.d.ts
  ui/packages/translators/vite.config.mts
Labels: kind/feature, size/XXL, approved, lgtm

#133 add docs for i18n-tool
  ui/packages/i18n-tool/README.md
  ui/packages/i18n-tool/package.json
  ui/packages/i18n-tool/src/index.js
  ui/packages/i18n-tool/src/scan/glossary.js
  ui/packages/i18n-tool/src/scan/index.js
  ui/packages/i18n-tool/src/scan/translate.js
  ui/pnpm-lock.yaml
Labels: kind/feature, size/XXL, kind/documentation, approved, lgtm

#134 feat: update locale file format & add extra log
  ui/packages/i18n-tool/src/scan/translate.js
Labels: approved, size/XS, kind/flake, lgtm

#135 integration with i18n-tool
  ui/apps/dashboard/18n.config.js
  ui/apps/dashboard/i18n.config.cjs
  ui/apps/dashboard/locales/en-US.json
  ui/apps/dashboard/locales/glossaries.csv
  ui/apps/dashboard/locales/zh-CN.json
  ui/apps/dashboard/package.json
  ui/apps/dashboard/src/pages/cluster-manage/index.tsx
  ui/apps/dashboard/src/pages/multicloud-policy-manage/propagation-policy/index.tsx
  ui/apps/dashboard/src/pages/multicloud-policy-manage/propagation-policy/propagation-policy-editor-drawer.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/config/components/config-editor-modal.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/config/components/configmap-table.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/config/components/query-filter.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/config/components/secret-table.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/config/index.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/index.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/new-workload-editor-modal.tsx
  ui/pnpm-lock.yaml
Labels: kind/feature, size/XXL, approved, lgtm

#136 📝 docs(ui): Small update to make the prompts more formal.
  ui/apps/dashboard/locales/en-US.json
  ui/apps/dashboard/locales/zh-CN.json
Labels: kind/documentation, approved, size/XS, lgtm

#137 feat: add ui for job and cronjob
  ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/index.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/new-workload-editor-modal.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/workload-detail-drawer.tsx
Labels: kind/feature, approved, lgtm, size/M

#138 feat: add api for clusterpropagationpolicy resource
  cmd/api/app/api.go
  cmd/api/app/routes/clusterpropagationpolicy/handler.go
  pkg/common/types/resourcekind.go
  pkg/resource/clusterpropagationpolicy/common.go
  pkg/resource/clusterpropagationpolicy/detail.go
  pkg/resource/clusterpropagationpolicy/list.go
Labels: kind/feature, approved, size/L, tide/merge-method-squash, lgtm

#139 UI for service
  ui/apps/dashboard/locales/en-US.json
  ui/apps/dashboard/locales/zh-CN.json
  ui/apps/dashboard/src/layout/index.tsx
  ui/apps/dashboard/src/layout/sidebar.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/service/components/ingress-table.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/service/components/service-editor-modal.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/service/components/service-table.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/service/index.tsx
  ui/apps/dashboard/src/services/base.ts
  ui/apps/dashboard/src/services/service.ts
Labels: kind/feature, size/XL, approved, lgtm
