Repository karmada-io/dashboard, pull requests merged in 2024-12, with the labels that each got.

#151 feat: rest api for op and cluster op
  cmd/api/app/api.go
  cmd/api/app/routes/clusteroverridepolicy/handler.go
  cmd/api/app/routes/overridepolicy/handler.go
  cmd/api/app/types/api/v1/overridepolicy.go
  pkg/common/types/resourcekind.go
  pkg/resource/clusteroverridepolicy/common.go
  pkg/resource/clusteroverridepolicy/detail.go
  pkg/resource/clusteroverridepolicy/list.go
  pkg/resource/overridepolicy/common.go
  pkg/resource/overridepolicy/detail.go
  pkg/resource/overridepolicy/list.go
Labels: kind/feature, size/XL, approved, tide/merge-method-squash, lgtm

#152 feat: ui for op and cluster op
  ui/apps/dashboard/src/pages/multicloud-policy-manage/override-policy/index.tsx
  ui/apps/dashboard/src/pages/multicloud-policy-manage/override-policy/override-policy-editor-drawer.tsx
  ui/apps/dashboard/src/services/overridepolicy.ts
Labels: kind/feature, size/XL, approved, lgtm

#153 feat: optimize the ui for pp
  ui/apps/dashboard/src/pages/multicloud-policy-manage/propagation-policy/index.tsx
  ui/apps/dashboard/src/pages/multicloud-policy-manage/propagation-policy/propagation-policy-editor-drawer.tsx
  ui/apps/dashboard/src/services/propagationpolicy.ts
Labels: kind/feature, approved, size/L, lgtm

#148 Karmada Metrics Backend
  .gitignore
  cmd/metrics-scraper/app/db/consts.go
  cmd/metrics-scraper/app/db/models.go
  cmd/metrics-scraper/app/metricsscraper.go
  cmd/metrics-scraper/app/options/options.go
  cmd/metrics-scraper/app/router/setup.go
  cmd/metrics-scraper/app/routes/metrics/handler.go
  cmd/metrics-scraper/app/routes/metrics/handlerqueries.go
  cmd/metrics-scraper/app/scrape/consts.go
  cmd/metrics-scraper/app/scrape/db.go
  cmd/metrics-scraper/app/scrape/job.go
  cmd/metrics-scraper/app/scrape/other.go
  cmd/metrics-scraper/app/scrape/scrape.go
  cmd/metrics-scraper/main.go
  go.mod
  go.sum
Labels: kind/feature, size/XXL, approved, lgtm
