Repository karmada-io/dashboard, pull requests merged in 2024-06, with the labels that each got.

#42 Enable dependabot
  .github/dependabot.yml
Labels: kind/cleanup, approved, size/S, lgtm

#50 build: upgrade github actions
  .github/workflows/push-image.yml
Labels: kind/bug, approved, size/S, lgtm

#54 add wenjiang and samzong onto the owner list
  OWNERS
Labels: kind/cleanup, approved, size/XS, lgtm
