Repository karmada-io/dashboard, pull requests merged in 2024-09, with the labels that each got.

#97 PathPrefix for karmada dashboard
  cmd/web/app/options/options.go
  cmd/web/app/web.go
  go.mod
  pkg/config/config.go
  pkg/config/model.go
  ui/apps/dashboard/index.html
  ui/apps/dashboard/package.json
  ui/apps/dashboard/src/routes/index.tsx
  ui/apps/dashboard/src/services/base.ts
  ui/apps/dashboard/src/vite-env.d.ts
  ui/apps/dashboard/vite.config.ts
  ui/pnpm-lock.yaml
Labels: kind/feature, size/XL, approved, lgtm

#98 feat: implement replace-path-prefix vite plugin, for local dev
  ui/apps/dashboard/vite.config.ts
Labels: kind/feature, approved, size/S, lgtm

#99 secret manage
  cmd/api/app/api.go
  cmd/api/app/routes/secret/handler.go
  pkg/resource/secret/common.go
  pkg/resource/secret/detail.go
  pkg/resource/secret/list.go
  ui/apps/dashboard/src/pages/multicloud-resource-manage/config/components/query-filter.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/config/components/secret-table.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/config/index.tsx
  ui/apps/dashboard/src/services/config.ts
Labels: kind/feature, approved, size/L, lgtm

#101 Bump Karmada dependencies to v1.11.0
  .github/workflows/push-image.yml
  cmd/api/app/routes/cluster/accesscluster.go
  go.mod
  go.sum
Labels: kind/cleanup, approved, size/L, lgtm

#100 daemonset manage
  cmd/api/app/api.go
  cmd/api/app/routes/daemonset/handler.go
  pkg/resource/common/resourcechannels.go
  pkg/resource/daemonset/common.go
  pkg/resource/daemonset/detail.go
  pkg/resource/daemonset/list.go
  ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/index.tsx
  ui/apps/dashboard/src/services/base.ts
  ui/apps/dashboard/src/services/workload.ts
Labels: kind/feature, approved, size/L, lgtm

#103 Update default image tag
  artifacts/dashboard/karmada-dashboard-api.yaml
  artifacts/dashboard/karmada-dashboard-web.yaml
Labels: kind/cleanup, approved, size/XS, lgtm

#87 fix: kind cluster config member2
  artifacts/kindClusterConfig/member2.yaml
Labels: approved, size/XS, lgtm

#104 kustomize deploy
  .gitignore
  artifacts/dashboard/karmada-dashboard-api.yaml
  artifacts/dashboard/karmada-dashboard-web.yaml
  artifacts/dashboard/kustomization.yaml
  artifacts/overlays/ingress-mode/dashboard-config.yaml
  artifacts/overlays/ingress-mode/ingress.yaml
  artifacts/overlays/ingress-mode/kustomization.yaml
  artifacts/overlays/nodeport-mode/dashboard-config.yaml
  artifacts/overlays/nodeport-mode/kustomization.yaml
Labels: kind/feature, approved, size/L, tide/merge-method-squash, lgtm

#108 fix: update logo in index template
  ui/apps/dashboard/index.html
  ui/apps/dashboard/public/logo.svg
  ui/apps/dashboard/public/vite.svg
Labels: kind/bug, approved, tide/merge-method-squash, lgtm, size/M

#105 doc: add new version of readme
  README.md
  README_cn.md
  docs/images/readme-dashboard-cn.png
  docs/images/readme-dashboard-en.png
  docs/images/readme-login-cn.png
  docs/images/readme-login-en.png
Labels: kind/documentation, approved, size/L, lgtm

#109 Update Readme with meeting info
  README.md
  README_cn.md
Labels: kind/cleanup, approved, lgtm, size/M

#110 fix: script typo error in cn readme
  README_cn.md
Labels: kind/bug, approved, tide/merge-method-squash, size/XS, lgtm

#111 feat: add api for job resource
  cmd/api/app/api.go
  cmd/api/app/routes/job/handler.go
  pkg/resource/common/resourcechannels.go
  pkg/resource/job/common.go
  pkg/resource/job/detail.go
  pkg/resource/job/events.go
  pkg/resource/job/list.go
  pkg/resource/job/pods.go
Labels: kind/feature, approved, size/L, lgtm

#112 feat: add api for cronjob resources
  cmd/api/app/api.go
  cmd/api/app/routes/cronjob/handler.go
  pkg/resource/common/resourcechannels.go
  pkg/resource/cronjob/common.go
  pkg/resource/cronjob/detail.go
  pkg/resource/cronjob/events.go
  pkg/resource/cronjob/jobs.go
  pkg/resource/cronjob/list.go
Labels: approved, size/L, kind/design, lgtm

#114 feature: add service management
  cmd/api/app/api.go
  cmd/api/app/routes/service/handler.go
  pkg/resource/common/endpoint.go
  pkg/resource/common/resourcechannels.go
  pkg/resource/common/serviceport.go
  pkg/resource/endpoint/endpoint.go
  pkg/resource/endpoint/list.go
  pkg/resource/service/common.go
  pkg/resource/service/detail.go
  pkg/resource/service/events.go
  pkg/resource/service/list.go
Labels: kind/feature, size/XL, approved, lgtm

#115 ci: setup ci-workflow for PR
  .github/workflows/ci.yml
  Makefile
Labels: kind/feature, approved, tide/merge-method-squash, lgtm, size/M

#124 charts: add the missing dashboard configmap
  .github/workflows/ci.yml
  charts/karmada-dashboard/templates/karmada-dashboard-configmap.yaml
  charts/karmada-dashboard/templates/karmada-dashboard-web.yaml
Labels: kind/bug, approved, size/L, tide/merge-method-squash, lgtm

#126 charts: fix several bugs, make the default config work
  charts/karmada-dashboard/templates/_helpers.tpl
  charts/karmada-dashboard/templates/karmada-dashboard-api.yaml
  charts/karmada-dashboard/templates/karmada-dashboard-sa.yaml
  charts/karmada-dashboard/templates/karmada-dashboard-web-service.yaml
  charts/karmada-dashboard/values.yaml
Labels: kind/bug, approved, lgtm, size/M

#129 charts: support configuring nodePort for the dashboard web
  charts/karmada-dashboard/templates/karmada-dashboard-web-service.yaml
  charts/karmada-dashboard/values.yaml
Labels: kind/feature, approved, size/XS, lgtm
