Repository karmada-io/dashboard, pull requests merged in 2025-09, with the labels that each got.

#251 Bump Karmada dependencies to v1.15.0
  go.mod
  go.sum
  pkg/resource/endpoint/endpoint.go
  pkg/resource/endpoint/list.go
Labels: kind/cleanup, approved, size/L, lgtm

#258 Add E2E tests for Workloads/Daemonset in the dashboard
  ui/apps/dashboard/e2e/workload/daemonset/daemonset-create.spec.ts
  ui/apps/dashboard/e2e/workload/daemonset/daemonset-delete.spec.ts
  ui/apps/dashboard/e2e/workload/daemonset/daemonset-edit.spec.ts
  ui/apps/dashboard/e2e/workload/daemonset/daemonset-list.spec.ts
  ui/apps/dashboard/e2e/workload/daemonset/daemonset-view.spec.ts
  ui/apps/dashboard/e2e/workload/daemonset/test-utils.ts
  ui/apps/dashboard/package.json
  ui/apps/dashboard/playwright.config.ts
  ui/pnpm-lock.yaml
Labels: size/XXL, approved, lgtm

#256 Bump github.com/golang-jwt/jwt to v5.3.0
  go.mod
  go.sum
Labels: kind/cleanup, approved, size/XS, lgtm

#257 Add E2E tests for Workloads/Cronjob in the dashboard
  ui/apps/dashboard/e2e/test-utils.ts
  ui/apps/dashboard/e2e/workload/cronjob/cronjob-create.spec.ts
  ui/apps/dashboard/e2e/workload/cronjob/cronjob-delete.spec.ts
  ui/apps/dashboard/e2e/workload/cronjob/cronjob-edit.spec.ts
  ui/apps/dashboard/e2e/workload/cronjob/cronjob-list.spec.ts
  ui/apps/dashboard/e2e/workload/cronjob/cronjob-view.spec.ts
  ui/apps/dashboard/e2e/workload/cronjob/test-utils.ts
  ui/apps/dashboard/e2e/workload/daemonset/test-utils.ts
  ui/apps/dashboard/e2e/workload/deployment/test-utils.ts
Labels: size/XL, approved, lgtm

#274 feat(config): add base configuration for MCP integration
  Makefile
  cmd/api/app/options/options.go
  pkg/config/config.go
Labels: kind/feature, approved, lgtm, size/M

#278 Refactor E2E tests to reduce duplicate code in the dashboard
  ui/apps/dashboard/e2e/test-utils.ts
  ui/apps/dashboard/e2e/workload/cronjob/cronjob-create.spec.ts
  ui/apps/dashboard/e2e/workload/cronjob/cronjob-delete.spec.ts
  ui/apps/dashboard/e2e/workload/cronjob/cronjob-edit.spec.ts
  ui/apps/dashboard/e2e/workload/cronjob/cronjob-list.spec.ts
  ui/apps/dashboard/e2e/workload/cronjob/cronjob-view.spec.ts
  ui/apps/dashboard/e2e/workload/cronjob/test-utils.ts
  ui/apps/dashboard/e2e/workload/daemonset/daemonset-create.spec.ts
  ui/apps/dashboard/e2e/workload/daemonset/daemonset-delete.spec.ts
  ui/apps/dashboard/e2e/workload/daemonset/daemonset-edit.spec.ts
  ui/apps/dashboard/e2e/workload/daemonset/daemonset-list.spec.ts
  ui/apps/dashboard/e2e/workload/daemonset/daemonset-view.spec.ts
  ui/apps/dashboard/e2e/workload/daemonset/test-utils.ts
  ui/apps/dashboard/e2e/workload/deployment/deployment-create.spec.ts
  ui/apps/dashboard/e2e/workload/deployment/deployment-delete.spec.ts
  ui/apps/dashboard/e2e/workload/deployment/deployment-edit.spec.ts
  ui/apps/dashboard/e2e/workload/deployment/deployment-list.spec.ts
  ui/apps/dashboard/e2e/workload/deployment/deployment-view.spec.ts
  ui/apps/dashboard/e2e/workload/deployment/test-utils.ts
  ui/apps/dashboard/playwright.config.ts
Labels: size/XXL, approved, lgtm

#259 Add E2E tests for Workloads/Job in the dashboard
  ui/apps/dashboard/e2e/test-utils.ts
  ui/apps/dashboard/e2e/workload/job/job-create.spec.ts
  ui/apps/dashboard/e2e/workload/job/job-delete.spec.ts
  ui/apps/dashboard/e2e/workload/job/job-edit.spec.ts
  ui/apps/dashboard/e2e/workload/job/job-list.spec.ts
  ui/apps/dashboard/e2e/workload/job/job-view.spec.ts
  ui/apps/dashboard/e2e/workload/job/test-utils.ts
Labels: approved, size/L, lgtm
