Repository karmada-io/dashboard, pull requests merged in 2025-02, with the labels that each got.

#185 [CVE-2024-45337] [CVE-2024-45338] Bump `golang.org/x/crypto` to `v0.32.0` and `golang.org/x/net` to `v0.34.0` to address CVE concerns
  go.mod
  go.sum
Labels: kind/cleanup, approved, lgtm, size/M

#186 fix: update the version of pnpm in ci
  .github/workflows/ci.yml
Labels: kind/bug, approved, size/XS, lgtm

#183 chore: format code about exported function should have comment
  cmd/api/app/options/options.go
  cmd/api/app/types/api/v1/config.go
  cmd/api/app/types/common/response.go
  cmd/metrics-scraper/app/options/options.go
  cmd/metrics-scraper/app/routes/metrics/handler.go
  cmd/metrics-scraper/app/routes/metrics/handlerqueries.go
  cmd/metrics-scraper/app/scrape/job.go
  cmd/metrics-scraper/app/scrape/scrape.go
  cmd/web/app/options/options.go
  pkg/client/auth.go
  pkg/client/verber.go
  pkg/common/errors/errors.go
  pkg/common/errors/handler.go
  pkg/common/errors/validate.go
  pkg/config/model.go
  pkg/resource/clusteroverridepolicy/common.go
  pkg/resource/clusteroverridepolicy/detail.go
  pkg/resource/clusteroverridepolicy/list.go
  pkg/resource/clusterpropagationpolicy/common.go
  pkg/resource/clusterpropagationpolicy/detail.go
  pkg/resource/configmap/common.go
  pkg/resource/cronjob/jobs.go
  pkg/resource/deployment/common.go
  pkg/resource/endpoint/endpoint.go
  pkg/resource/endpoint/list.go
  pkg/resource/event/common.go
  pkg/resource/ingress/common.go
  pkg/resource/ingress/filter.go
  pkg/resource/ingress/list.go
  pkg/resource/job/list.go
  pkg/resource/node/common.go
  pkg/resource/overridepolicy/list.go
  pkg/resource/pod/common.go
  pkg/resource/pod/detail.go
  pkg/resource/pod/list.go
  pkg/resource/propagationpolicy/list.go
  pkg/resource/secret/common.go
  pkg/resource/secret/list.go
  pkg/resource/service/common.go
  pkg/resource/statefulset/common.go
Labels: kind/cleanup, approved, lgtm, size/M

#187 fix delete namespace in control plane
  cmd/api/app/routes/unstructured/handler.go
  ui/apps/dashboard/src/pages/multicloud-resource-manage/namespace/index.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/index.tsx
  ui/apps/dashboard/src/services/workload.ts
Labels: kind/bug, approved, size/S, tide/merge-method-squash, lgtm

#188 chore: format code about errcheck,gosimple,ineffassign,unused
  cmd/api/app/api.go
  cmd/api/app/routes/cluster/accesscluster.go
  cmd/api/app/routes/cluster/handler.go
  cmd/api/app/routes/clusteroverridepolicy/handler.go
  cmd/api/app/routes/clusterpropagationpolicy/handler.go
  cmd/metrics-scraper/app/metricsscraper.go
  cmd/metrics-scraper/app/routes/metrics/handlerqueries.go
  cmd/metrics-scraper/app/scrape/other.go
  cmd/metrics-scraper/app/scrape/scrape.go
  cmd/web/app/web.go
  hack/verify-staticcheck.sh
  pkg/common/errors/handler.go
  pkg/environment/version.go
Labels: kind/cleanup, approved, size/L, lgtm

#190 fix create service
  ui/apps/dashboard/locales/en-US.json
  ui/apps/dashboard/locales/zh-CN.json
  ui/apps/dashboard/src/pages/multicloud-resource-manage/service/components/ingress-table.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/service/components/service-editor-modal.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/service/index.tsx
  ui/apps/dashboard/src/services/service.ts
Labels: kind/bug, approved, size/L, tide/merge-method-squash, lgtm

#191 chore: format code about revive
  .golangci.yml
  cmd/api/app/api.go
  cmd/api/app/routes/configmap/handler.go
  cmd/api/app/routes/cronjob/handler.go
  cmd/api/app/routes/daemonset/handler.go
  cmd/api/app/routes/deployment/handler.go
  cmd/api/app/routes/ingress/handler.go
  cmd/api/app/routes/job/handler.go
  cmd/api/app/routes/member/member.go
  cmd/api/app/routes/namespace/handler.go
  cmd/api/app/routes/overridepolicy/handler.go
  cmd/api/app/routes/overview/misc.go
  cmd/api/app/routes/propagationpolicy/handler.go
  cmd/api/app/routes/secret/handler.go
  cmd/api/app/routes/service/handler.go
  cmd/api/app/routes/statefulset/handler.go
  cmd/api/app/types/api/v1/cluster.go
  cmd/api/app/types/common/request.go
  cmd/api/main.go
  cmd/metrics-scraper/app/metricsscraper.go
  cmd/metrics-scraper/app/scrape/db.go
  cmd/metrics-scraper/app/scrape/other.go
  cmd/web/app/options/options.go
  cmd/web/app/web.go
  hack/verify-staticcheck.sh
  pkg/client/client.go
  pkg/client/init.go
  pkg/client/verber.go
  pkg/config/config.go
  pkg/config/model.go
  pkg/dataselect/dataselect.go
  pkg/dataselect/dataselect_test.go
  pkg/dataselect/pagination.go
  pkg/dataselect/stdcomparabletypes.go
  pkg/resource/cluster/cluster.go
  pkg/resource/cluster/common.go
  pkg/resource/cluster/detail.go
  pkg/resource/clusteroverridepolicy/common.go
  pkg/resource/clusterpropagationpolicy/common.go
  pkg/resource/configmap/common.go
  pkg/resource/cronjob/common.go
  pkg/resource/daemonset/common.go
  pkg/resource/deployment/common.go
  pkg/resource/event/common.go
  pkg/resource/ingress/common.go
  pkg/resource/job/common.go
  pkg/resource/namespace/common.go
  pkg/resource/node/common.go
  pkg/resource/overridepolicy/common.go
  pkg/resource/overridepolicy/list.go
  pkg/resource/pod/common.go
  pkg/resource/propagationpolicy/common.go
  pkg/resource/propagationpolicy/list.go
  pkg/resource/secret/common.go
  pkg/resource/service/common.go
  pkg/resource/service/detail.go
  pkg/resource/statefulset/common.go
Labels: kind/cleanup, approved, size/L, lgtm

#189 chore: format code about gocyclo,gosec
  cmd/api/app/routes/overview/misc.go
  cmd/metrics-scraper/app/routes/metrics/handlerqueries.go
  cmd/metrics-scraper/app/scrape/other.go
  hack/verify-staticcheck.sh
  pkg/common/errors/localizer.go
Labels: kind/cleanup, approved, size/L, lgtm

#193 opt namespace UI
  ui/apps/dashboard/locales/en-US.json
  ui/apps/dashboard/locales/zh-CN.json
  ui/apps/dashboard/src/pages/multicloud-resource-manage/namespace/index.tsx
  ui/apps/dashboard/src/pages/overview/index.tsx
Labels: kind/feature, approved, tide/merge-method-squash, lgtm, size/M

#194 fix tab-switch in workload page
  ui/apps/dashboard/locales/en-US.json
  ui/apps/dashboard/locales/zh-CN.json
  ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/index.tsx
  ui/apps/dashboard/src/services/overridepolicy.ts
Labels: kind/bug, approved, size/S, tide/merge-method-squash, lgtm

#195 fix: update related resources for propagationpolicy
  pkg/resource/propagationpolicy/list.go
  ui/apps/dashboard/src/pages/multicloud-policy-manage/propagation-policy/index.tsx
  ui/apps/dashboard/src/services/propagationpolicy.ts
Labels: kind/bug, approved, lgtm, size/M

#196 fix: create sa resource in control-plane with helm chart
  charts/karmada-dashboard/templates/karmada-dashboard-clean-serviceaccount.yaml
  charts/karmada-dashboard/templates/karmada-dashboard-init-serviceaccount.yaml
  charts/karmada-dashboard/templates/karmada-dashboard-serviceaccount-configmap.yaml
  charts/karmada-dashboard/templates/karmada-dashboard-serviceaccount.yaml
Labels: kind/bug, approved, size/L, tide/merge-method-squash, lgtm

#203 add ci for latest/released chart
  .github/workflows/dockerhub-latest-chart.yml
  .github/workflows/dockerhub-released-chart.yml
  Makefile
  hack/package-helm-chart.sh
  hack/util.sh
Labels: kind/feature, size/XL, approved, tide/merge-method-squash, lgtm

#202 add ci for latest/released image
  .github/workflows/dockerhub-latest-image.yml
  .github/workflows/dockerhub-released-image.yml
Labels: kind/feature, approved, size/L, lgtm
