Repository karmada-io/dashboard, pull requests merged in 2025-05, with the labels that each got.

#174 ci: add multi-platform image build for karmada-dashboard
  .github/workflows/push-image.yml
  Makefile
  cluster/images/Dockerfile
  cluster/images/build-web.Dockerfile
  cluster/images/buildx.Dockerfile
Labels: kind/feature, approved, lgtm, size/M

#209 clean: rm ustc alpine mirror
  cluster/images/Dockerfile
  cluster/images/build-web.Dockerfile
  cluster/images/buildx.Dockerfile
Labels: kind/cleanup, approved, size/XS, lgtm

#211 add Dockerfile for Karmada Dashboard web terminal
  cluster/images/build-terminal.Dockerfile
Labels: approved, lgtm, size/M
