Repository karmada-io/dashboard, pull requests merged in 2025-01, with the labels that each got.

#157 Bump Karmada dependencies to v1.12.1
  go.mod
  go.sum
Labels: kind/cleanup, approved, size/L, lgtm

#158 [CVE-2024-51744] Bump jwt to v5.2.1 to address CVE concerns
  cmd/api/app/routes/auth/me.go
  go.mod
  go.sum
Labels: kind/cleanup, approved, size/XS, lgtm

#163 clean duplicate code & warning in dashboard ui
  ui/apps/dashboard/src/App.tsx
  ui/apps/dashboard/src/components/navigation/index.tsx
  ui/apps/dashboard/src/components/tag-list/helper.ts
  ui/apps/dashboard/src/components/tag-list/index.tsx
Labels: kind/cleanup, approved, tide/merge-method-squash, lgtm, size/M

#160 Enhancement README file
  README.md
  README_cn.md
  artifacts/dashboard/karmada-dashboard-api.yaml
Labels: kind/documentation, approved, size/L, lgtm

#166 add fallback value to i18n and fix inconsistent probelm
  ui/apps/dashboard/locales/en-US.json
  ui/apps/dashboard/locales/zh-CN.json
  ui/apps/dashboard/src/pages/cluster-manage/index.tsx
  ui/apps/dashboard/src/pages/cluster-manage/new-cluster-modal.tsx
  ui/apps/dashboard/src/pages/login/index.tsx
  ui/apps/dashboard/src/pages/multicloud-policy-manage/override-policy/index.tsx
  ui/apps/dashboard/src/pages/multicloud-policy-manage/override-policy/override-policy-editor-drawer.tsx
  ui/apps/dashboard/src/pages/multicloud-policy-manage/propagation-policy/index.tsx
  ui/apps/dashboard/src/pages/multicloud-policy-manage/propagation-policy/propagation-policy-editor-drawer.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/config/components/config-editor-modal.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/config/components/configmap-table.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/config/components/secret-table.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/namespace/index.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/namespace/new-namespace-modal.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/service/components/ingress-table.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/service/components/service-editor-modal.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/service/components/service-table.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/service/index.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/index.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/new-workload-editor-modal.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/workload-detail-drawer.tsx
  ui/apps/dashboard/src/pages/overview/index.tsx
  ui/apps/dashboard/src/routes/route.tsx
  ui/apps/dashboard/src/services/base.ts
Labels: kind/bug, size/XXL, kind/cleanup, approved, tide/merge-method-squash, lgtm

#162 Remove unnecessary hack folder.
  hack/build.sh
  hack/deploy-agent-and-estimator.sh
  hack/deploy-k8s-metrics-server.sh
  hack/deploy-karmada-agent.sh
  hack/deploy-karmada.sh
  hack/deploy-scheduler-estimator.sh
  hack/local-down-karmada.sh
  hack/local-up-karmada.sh
  hack/util/constant.sh
  hack/util/git.sh
  hack/util/misc.sh
  hack/version.sh
Labels: size/XXL, kind/cleanup, approved, lgtm

#167 pin github action runner to ubuntu-22.04 not the latest
  .github/workflows/codeql-analysis.yml
  .github/workflows/push-image.yml
Labels: kind/cleanup, approved, size/XS, lgtm

#171 update Makefile, make development simpler
  .gitignore
  Makefile
Labels: kind/feature, approved, size/L, lgtm

#170 Update localization files for English and Chinese
  ui/apps/dashboard/locales/en-US.json
  ui/apps/dashboard/locales/zh-CN.json
Labels: kind/feature, approved, size/L, lgtm

#173 fix duration for workload
  ui/apps/dashboard/src/main.tsx
  ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/workload-detail-drawer.tsx
  ui/apps/dashboard/src/utils/time.ts
Labels: kind/bug, approved, size/L, lgtm

#180 chore: format code about whitespace
  cmd/metrics-scraper/app/scrape/other.go
  hack/verify-staticcheck.sh
  pkg/client/init.go
  pkg/dataselect/dataselect_test.go
  pkg/resource/common/resourcechannels.go
  pkg/resource/cronjob/detail.go
  pkg/resource/cronjob/events.go
  pkg/resource/cronjob/jobs.go
  pkg/resource/cronjob/list.go
  pkg/resource/daemonset/common.go
  pkg/resource/daemonset/detail.go
  pkg/resource/daemonset/list.go
  pkg/resource/deployment/detail.go
  pkg/resource/deployment/list.go
  pkg/resource/job/events.go
  pkg/resource/job/list.go
  pkg/resource/statefulset/list.go
Labels: kind/cleanup, approved, lgtm, size/M

#181 chore: format code about misspell,staticcheck,govet
  cmd/api/app/routes/cluster/handler.go
  cmd/api/app/routes/clusteroverridepolicy/handler.go
  cmd/api/app/routes/clusterpropagationpolicy/handler.go
  cmd/api/app/routes/overridepolicy/handler.go
  cmd/api/app/routes/overview/misc.go
  cmd/api/app/routes/propagationpolicy/handler.go
  hack/verify-staticcheck.sh
  pkg/client/init.go
  pkg/config/config.go
  pkg/resource/cronjob/jobs.go
Labels: kind/cleanup, approved, lgtm, size/M

#179 format code about exported function should have comment
  cmd/api/app/router/middleware.go
  cmd/api/app/router/setup.go
  cmd/api/app/routes/cluster/accesscluster.go
  cmd/api/app/routes/cluster/handler.go
  cmd/api/app/routes/config/handler.go
  cmd/api/app/routes/overview/misc.go
  cmd/api/app/types/api/v1/auth.go
  cmd/api/app/types/api/v1/cluster.go
  cmd/api/app/types/api/v1/deployment.go
  cmd/api/app/types/api/v1/namespace.go
  cmd/api/app/types/api/v1/overridepolicy.go
  cmd/api/app/types/api/v1/overview.go
  cmd/api/app/types/api/v1/propagationpolicy.go
  cmd/metrics-scraper/app/db/consts.go
  cmd/metrics-scraper/app/db/models.go
  cmd/metrics-scraper/app/router/setup.go
  pkg/client/client.go
  pkg/client/init.go
  pkg/config/config.go
  pkg/config/model.go
  pkg/dataselect/dataselectquery.go
  pkg/dataselect/stdcomparabletypes.go
  pkg/environment/version.go
  pkg/resource/cluster/cluster.go
  pkg/resource/cluster/common.go
  pkg/resource/cluster/detail.go
  pkg/resource/clusterpropagationpolicy/list.go
  pkg/resource/cronjob/common.go
  pkg/resource/daemonset/common.go
  pkg/resource/job/common.go
  pkg/resource/namespace/common.go
  pkg/resource/node/list.go
  pkg/resource/overridepolicy/common.go
  pkg/resource/propagationpolicy/common.go
Labels: kind/cleanup, approved, size/L, lgtm
